CREATE TABLE IF NOT EXISTS ConversionTracker (
  accountId  Int64,
  allConversionValue  String,
  allConversions  Int64,
  appConversion_appConversionType  String,
  appConversion_appId  String,
  appConversion_appPlatform  String,
  appConversion_appPostbackUrl_url  String,
  appConversion_snippetId  Int64,
  appConversion_snippetLabel  String,
  category  String,
  conversionCountingType  String,
  conversionTrackerId  Int64,
  conversionTrackerName  String,
  conversionTrackerTrackId  Int64,
  conversionTrackerType  String,
  conversionValue  String,
  conversions  Int64,
  excludeFromBidding  String,
  measurementPeriod  Int64,
  mostRecentConversionDate  String,
  status  String,
  userRevenueValue  String,
  webConversion_advancedSnippet  String,
  webConversion_markupLanguage  String,
  webConversion_snippet  String,
  webConversion_trackingCodeType  String
) Engine = Log
