CREATE TABLE IF NOT EXISTS AdGroup (
  accountId Int64,
  adGroupBiddingStrategy_campaignBiddingStrategyType String,
  adGroupBiddingStrategy_maxCpcBidValue Int64,
  adGroupBiddingStrategy_maxCpvBidValue Int64,
  adGroupBiddingStrategy_maxVcpmBidValue Int64,
  adGroupBiddingStrategy_targetCpaBidValue Int64,
  adGroupId Int64,
  adGroupName String,
  campaignId Int64,
  campaignName String,
  conversionOptimizer_manualConversionOptimizer_eligibilityFlg String,
  conversionOptimizer_optimizerType String,
  createdDate String,
  deviceApp_0 String,
  deviceApp_1 String,
  deviceOsVersion String,
  deviceOs_0 String,
  deviceOs_1 String,
  device_0 String,
  device_1 String,
  device_2 String,
  userStatus String
) Engine = Log
